## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [14]:
import numpy as np
import pandas as pd

#Set random seed for reproducibilty
np.random.seed(123)

#Creating a datafranme with 2 classes
n_samples=1000
class_0_ratio=0.9
n_class_0=int(n_samples*class_0_ratio)
n_class_1=n_samples-n_class_0

In [15]:
n_class_1,n_class_0

(100, 900)

In [16]:
## CREATING DATAFRAME WITH IMBALANCED DATASET
class_0=pd.DataFrame({
    'feature1': np.random.normal(loc=0,scale=1, size=n_class_0),
    'feature2': np.random.normal(loc=0,scale=1, size=n_class_0),
    'target':[0]*n_class_0
})

class_1=pd.DataFrame({
    'feature_1':np.random.normal(loc=2,scale=1,size=n_class_1),
    'feature_2':np.random.normal(loc=2,scale=1,size=n_class_1),
    'target':[1]*n_class_1
})

In [17]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [18]:
df.tail()

     feature1  feature2  target  feature_1  feature_2
995       NaN       NaN       1   1.376371   2.845701
996       NaN       NaN       1   2.239810   0.880077
997       NaN       NaN       1   1.131760   1.640703
998       NaN       NaN       1   2.902006   0.390305
999       NaN       NaN       1   2.697490   2.013570

In [19]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [33]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [34]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [35]:
df_minority_upsampled.shape

(900, 5)

In [36]:
df_minority_upsampled.head()

     feature1  feature2  target  feature_1  feature_2
951       NaN       NaN       1   1.125854   1.843917
992       NaN       NaN       1   2.196570   1.397425
914       NaN       NaN       1   1.932170   2.998053
971       NaN       NaN       1   2.272825   3.034197
960       NaN       NaN       1   2.870056   1.550485

In [37]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [38]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [39]:
import pandas as pd

#Set random seed for reproducibility
np.random.seed(3123)

#Create a dataframe with 2 classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

#Checking the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [40]:
## DOWNSAMPLING

df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [54]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,
                               replace=False, #Sample With replacement
         n_samples=len(df_minority),
         random_state=42
        )

In [55]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [56]:
df_downsampled.shape

(200, 3)

In [57]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [ ]:
# Downsampling is bad because we are 
# losing the data points